name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          # Run build commands or scripts

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Run tests
        run: |
          # Run unit tests

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Zip source code and api_urls.json (DataAnalysis)
        run: |
          cd crypto-price-alert-dataanalysis
          zip -r crypto_price_alert_data_analysis_lambda.zip CryptoPriceAlert-DataAnalysis.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy DataAnalysis to AWS Lambda
        run: |
          aws lambda update-function-code --function-name CryptoPriceAlert-DataAnalysis --zip-file fileb://path/to/DataAnalysis/crypto_price_alert_data_analysis_lambda.zip

      - name: Zip source code and api_urls.json (DataCollection)
        run: |
          cd crypto-price-alert-datacollection
          zip -r crypto_price_alert_data_collection_lambda.zip CryptoPriceAlert-DataCollection.py api_urls.json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy DataCollection to AWS Lambda
        run: |
          aws lambda update-function-code --function-name CryptoPriceAlert-DataCollection --zip-file fileb://path/to/DataCollection/crypto_price_alert_data_collection_lambda.zip
