name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          # Run build commands or scripts

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Run tests
        run: |
          # Run unit tests

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Zip source code and api_urls.json
        run: |
          zip -r crypto_price_alert_lambda.zip crypto_price_alert_lambda.py api_urls.json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name CryptoPriceAlert --zip-file fileb://crypto_price_alert_lambda.zip
